name: Documentation Tests

on: [push, pull_request]

jobs:
  CheckDocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y git cmake graphviz libavahi-common-dev libavahi-client-dev libaio-dev libusb-1.0-0-dev libxml2-dev rpm tar bzip2 gzip flex bison git libzstd-dev doxygen pandoc
          mkdir build
          cd build
          cmake .. -DWITH_MAN=ON -DHAVE_DNS_SD=OFF
          make
          cd ..
          cd docs
          pip install -r requirements_doc.txt
          cd ..

      - name: Build man pages
        run: |
          cd docs
          python man_to_rst.py
          cd ..

      - name: Check doc build
        run: |
          cd docs
          make html SPHINXOPTS="-W"
          cd ..

    #   - name: Check doc coverage
    #     run: |
    #       cd docs
    #       make coverage
    #       cat build/coverage/python.txt
    #       cat build/coverage/python.txt | wc -l | xargs -I % test % -eq 2
    #       cd ..

      - name: Check doc links
        run: |
          cd docs
          make linkcheck
          cd ..